blueprint:
  name: Robb Smarrt 8-button switch for Deconz
  description:  |
    This blueprint is for the  Robb smarrt 8-button switch panel (ROBB ROB_200-007-0) when used with deconz.
    It is for general use so all buttons can be connected to any action of your choice. This remote supports short button clicks and long button presses (over 4 seconds)
    Make sure to select the correct (deconz connected) sensor for the remote.
    Original source from: https://github.com/Bekkie/ha-blueprints
  domain: automation
  source_url: https://github.com/geertdoornbos/ha-blueprints/blob/main/automation/robb-smarrt/ROB_200-007-0/8-button-deconz-ROB_200-007-0.yaml
  input:
    remote:
      name: Remote
      description: Switch remote to use
      selector:
        device:
          integration: deconz
          model: "ROB_200-007-0"
          
    on_button_1_short:
      name: On button 1 - short
      default: []
      selector:
        action: {}
    off_button_1_short:
      name: Off button 1 - short
      default: []
      selector:
        action: {}
    on_button_1_long:
      name: On button 1 - long press
      default: []
      selector:
        action: {}
    off_button_1_long:
      name: Off button 1 - long press
      default: []
      selector:
        action: {}

    on_button_2_short:
      name: On button 2 - short
      default: []
      selector:
        action: {}
    off_button_2_short:
      name: Off button 2 - short
      default: []
      selector:
        action: {}
    on_button_2_long:
      name: On button 2 - long press
      default: []
      selector:
        action: {}
    off_button_2_long:
      name: Off button 2 - long press
      default: []
      selector:
        action: {}

    on_button_3_short:
      name: On button 3 - short
      default: []
      selector:
        action: {}
    off_button_3_short:
      name: Off button 3 - short
      default: []
      selector:
        action: {}
    on_button_3_long:
      name: On button 3 - long press
      default: []
      selector:
        action: {}
    off_button_3_long:
      name: Off button 3 - long press
      default: []
      selector:
        action: {}

    on_button_4_short:
      name: On button 4 - short
      default: []
      selector:
        action: {}
    off_button_4_short:
      name: Off button 4 - short
      default: []
      selector:
        action: {}
    on_button_4_long:
      name: On button 4 - long press
      default: []
      selector:
        action: {}
    off_button_4_long:
      name: Off button 4 - long press
      default: []
      selector:
        action: {}


mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input "remote"
  
action:
  - variables:
      button: '{{ (trigger.event.data.event / 1000) | int }}'
      action: '{{ trigger.event.data.event % 10 }}'
  - choose:
      - conditions:
          - "{{ button == 1 and action == 2 }}"
        sequence: !input "on_button_1_short"
      - conditions:
          - "{{ button == 2 and action == 2 }}"
        sequence: !input "off_button_1_short"
      - conditions:
          - "{{ button == 3 and action == 2 }}"
        sequence: !input "on_button_2_short"
      - conditions:
          - "{{ button == 4 and action == 2 }}"
        sequence: !input "off_button_2_short"
      - conditions:
          - "{{ button == 5 and action == 2 }}"
        sequence: !input "on_button_3_short"
      - conditions:
          - "{{ button == 6 and action == 2 }}"
        sequence: !input "off_button_3_short"
      - conditions:
          - "{{ button == 7 and action == 2 }}"
        sequence: !input "on_button_4_short"
      - conditions:
          - "{{ button == 8 and action == 2 }}"
        sequence: !input "off_button_4_short"

      - conditions:
          - "{{ button == 1 and action == 1 }}"
        sequence: !input "on_button_1_long"
      - conditions:
          - "{{ button == 2 and action == 1 }}"
        sequence: !input "off_button_1_long"
      - conditions:
          - "{{ button == 3 and action == 1 }}"
        sequence: !input "on_button_2_long"
      - conditions:
          - "{{ button == 4 and action == 1 }}"
        sequence: !input "off_button_2_long"
      - conditions:
          - "{{ button == 5 and action == 1 }}"
        sequence: !input "on_button_3_long"
      - conditions:
          - "{{ button == 6 and action == 1 }}"
        sequence: !input "off_button_3_long"
      - conditions:
          - "{{ button == 7 and action == 1 }}"
        sequence: !input "on_button_4_long"
      - conditions:
          - "{{ button == 8 and action == 1 }}"
        sequence: !input "off_button_4_long"
